6 using namingstrategy for names resolving
devastool/entity2jooq pull request #22
Opened 2024-07-21 16:14 UTC by Vendeetta

Issue: https://github.com/orgs/devastool/projects/1?pane=issue&itemId=71445768

2024-07-21 17:03 UTC, andrey-yurzanov requested changes
Too raw yet

2024-07-22 19:48 UTC, Filkoof commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +   * @param type Class of naming strategy.
should we add @param args?

2024-07-22 19:58 UTC, Filkoof commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +    if (type != null) {
mb better to check it in beginning ?

Like:
```
if (type == null) {
    throw new IllegalArgumentException("Type must not be null");
}
```

2024-07-22 20:06 UTC, Filkoof commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +  }
It'll be readable if you extract create instance logic to private method. 

```
private <T> T createInstance(Class<T> type, Object[] args) {
    Class<?>[] argsTypes = Arrays.stream(args)
         .map(Object::getClass)
         .toArray(Class[]::new);
    return type.getConstructor(argsTypes).newInstance(args);
 }
```

and then you can just use `CACHE.computeIfAbsent(type, key -> createInstance(key, args))` and return provided value

2024-07-22 20:25 UTC, Filkoof commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +          throw new RuntimeException(e);
I supose this catch may be more informative. If we look at it from dev view, it's not realy obvious what we catch here. Narrow the abstraction, and we'll understand what we want to handle here. Or we want to handle every possible exception? 

But anyway we can make it more informative if add description:
`throw new RuntimeException("Failed to create an instance of " + type.getName(), e)`

2024-07-22 21:08 UTC, Filkoof commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +  Map<Class<?>, Object> CACHE = new HashMap<>();
miss modifiers

2024-07-23 08:08 UTC, Filkoof submitted a review, later dismissed

2024-07-23 10:57 UTC, andrey-yurzanov requested changes
Some comments

2024-07-23 10:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/ContextableFactory.java
> +   * Constructor.
See JavaDocs format here: [EntityColumnDefinition.java](https://github.com/devastool/entity2jooq/blob/7162c1f5e465f1c0d905b6e9d735126992e365f5/entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/EntityColumnDefinition.java#L32)

2024-07-23 10:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntitySchemaDefinitionFactory.java
> +    Class<? extends NamingStrategy> strategyClass = SnakeCaseStrategy.class;
`Class<? extends NamingStrategy> strategyClass = SnakeCaseStrategy.class;`
I think this is the wrong way. If class doesn't have `Schema` annotation or the field doesn't have `Column` annotation, you can use strategy from `Table` annotation. The default value in the annotation can change at any time, and it's too difficult to change all places where you wrote `SnakeCaseStrategy.class `.

2024-07-23 10:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityTableDefinitionFactory.java
> +        var strategy = (NamingStrategy) getContext().getInstance(tableAnnotation.naming());
`var strategy = (NamingStrategy) getContext().getInstance(tableAnnotation.naming());`
Doesn't work like this?
`var strategy = getContext().getInstance(tableAnnotation.naming());`

2024-07-23 10:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +package io.github.devastool.entity2jooq.codegen.definition.factory;
You need copyright header.
[Copyright example](https://github.com/devastool/entity2jooq/blob/7162c1f5e465f1c0d905b6e9d735126992e365f5/entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/filesystem/ExtFileVisitor.java#L1)

2024-07-23 10:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +    } catch (Exception e) {
Maybe `Exception exeception`?

2024-07-23 10:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +    return (T) CACHE.computeIfAbsent(type, v -> createInstance(type, args));
Maybe `value ->`?

2024-07-26 13:50 UTC, andrey-yurzanov requested changes
Some comments

2024-07-26 13:50 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/ContextableFactory.java
> +   * Getter
Returns instance of {@link FactoryContext }

2024-07-26 13:50 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +  public Optional<EntityColumnDefinition> build(Field field, TableDefinition table, Class<?> type) {
To use type is bad way, I think. You should have all information in `TableDefinition` already, so use `table.getNamingStrategy()`.

2024-07-26 13:50 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +  private NamingStrategy getNamingStrategy(Class<?> type, Column columnAnnotation) {
`Schema` is optional, just use `TableDefinition` instance.

2024-07-26 13:50 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +    return (T) CACHE.computeIfAbsent(type, v -> createInstance(type, args));
Maybe `value` ->?

2024-07-26 14:54 UTC, andrey-yurzanov requested changes

2024-07-26 14:54 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/EntityTableDefinition.java
> +  public Class<? extends NamingStrategy> getStrategy() {
Comments

2024-07-26 14:54 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContext.java
> +      var argsTypes = Arrays.stream(args)
`.stream(args)` to next line, please

2024-07-29 08:43 UTC, Filkoof submitted a review, later dismissed

2024-07-29 09:24 UTC, Sergio-Konovalov approved these changes

2024-07-29 12:27 UTC, andrey-yurzanov requested changes

2024-07-29 12:27 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/test/java/io/github/devastool/entity2jooq/codegen/definition/factory/FactoryContextTest.java
> +
unnecessary line

2024-07-29 13:49 UTC, andrey-yurzanov approved these changes

2024-07-29 14:04 UTC, Sergio-Konovalov approved these changes

2024-07-30 08:05 UTC, merged