Added support embedded objects Issue #12
devastool/entity2jooq pull request #24
Opened 2024-07-23 05:32 UTC by Sergio-Konovalov

2024-07-23 11:11 UTC, andrey-yurzanov requested changes
Some comments

2024-07-23 11:11 UTC, andrey-yurzanov commented on entity2jooq-example/src/main/java/io/github/devastool/entity2jooq/example/TestEntity.java
> + * @since 0.0.1
`@since 0.0.1`
Use `@since 1.0.0`

2024-07-23 11:11 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityTableDefinitionFactory.java
> +  private void accumulateColumnDefinition(Class<?> type, EntityTableDefinition table) {
1. No recursion, please
2. What happens if the field has a complex type, for example, HashMap? Maybe we need a specific annotation, like 'Embedded'? Example: 
```
@Embedded
public class TestEntityInfo {}
```
Think about it.

2024-07-26 15:18 UTC, andrey-yurzanov requested changes
Some comments

2024-07-29 08:37 UTC, Filkoof commented on entity2jooq-annotation/src/main/java/io/github/devastool/entity2jooq/annotation/AttributeOverride.java
> +
Do we need java dock description here?

2024-07-29 08:37 UTC, Filkoof commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/FieldPair.java
> +
unnecessary space here

2024-08-07 08:00 UTC, andrey-yurzanov requested changes
Some comments

2024-08-07 09:47 UTC, Vendeetta commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/FieldDetails.java
> +   * Returns the parent field of the field, or {@code null} if there is no parent field.
"field of the field" mistake?

2024-08-07 11:40 UTC, Sergio-Konovalov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +    ColumnOverrides columnOverrides = findAnnotation(annotations, ColumnOverrides.class);
Because if only one @ColumnOverride annotation is set on a field, it will be directly accessible, without the @ColumnOverrides container

2024-08-07 12:05 UTC, Sergio-Konovalov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +      if (fieldDetails.getType().isAnnotationPresent(Embedded.class)) {
But what if the nesting levels are more than 2?

2024-08-07 12:08 UTC, Sergio-Konovalov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +        Column column = fieldDetails.getField().getAnnotation(Column.class);
There are too many variables named field, I’ll remove them in the field.getFieldAnnotation() method

2024-08-07 12:22 UTC, Sergio-Konovalov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/FieldDetails.java
> +   * Returns the parent field of the field, or {@code null} if there is no parent field.
No, **parent field** of the field

2024-08-13 14:21 UTC, andrey-yurzanov requested changes
Some comments

2024-08-13 14:21 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +        overrideColumns.put(fieldName + DOT + override.name(), override.column());
```java
fieldName + DOT + override.name()
```
Use String.join()

2024-08-13 14:21 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +    if (StringUtils.isNotEmpty(newValue)) {
`StringUtils` do not use this class, please. Because it create dependency with package `org.apache.maven.shared.utils.StringUtils`. Just check it self: `newValue != null && !newValue.isEmpty()`

2024-08-13 14:21 UTC, andrey-yurzanov commented on entity2jooq-example/pom.xml
> +    <module>entity2jooq-example-embedded</module>
Why do you need separate module for embedded?

2024-08-14 07:57 UTC, andrey-yurzanov requested changes
Some comments

2024-08-14 07:57 UTC, andrey-yurzanov commented on entity2jooq-example/entity2jooq-example-h2/src/test/java/io/github/devastool/entity2jooq/example/TestEmbeddedEntityTest.java
> +
unnecessary line

2024-08-14 07:57 UTC, andrey-yurzanov commented on entity2jooq-example/entity2jooq-example-postgres/src/test/java/io/github/devastool/entity2jooq/example/TestEmbeddedEntityTest.java
> +
unnecessary line

2024-08-14 07:57 UTC, andrey-yurzanov commented on entity2jooq-codegen/src/main/java/io/github/devastool/entity2jooq/codegen/definition/factory/EntityColumnDefinitionFactory.java
> +  private Map<String, Column> getOverrideColumns(Field field) {
Move all private methods after public methods.

2024-08-14 08:01 UTC, andrey-yurzanov approved these changes

2024-08-14 18:51 UTC, Filkoof approved these changes

2024-08-16 08:02 UTC, Vendeetta approved these changes

2024-08-16 08:03 UTC, merged