29 MySQL dialect support
devastool/entity2jooq pull request #58
Opened 2024-08-24 12:32 UTC by Filkoof

add MySQL dialect support. Cover it with tests. 
ISSUE: 29-mysql-dialect-support

2024-08-25 04:44 UTC, Vendeetta submitted a review, later dismissed

2024-08-27 09:15 UTC, andrey-yurzanov requested changes

2024-08-27 09:15 UTC, andrey-yurzanov commented on entity2jooq-example/entity2jooq-example-mysql/src/main/java/io/github/devastool/entity2jooq/example/TestInheritEntity.java
> +
Unnecessary line

2024-09-02 13:14 UTC, andrey-yurzanov approved these changes

2024-09-02 13:14 UTC, merged